import { db, defaultBackgroundPreferences, defaultSettings, SYSTEM_EMOTIONS, initializeDb } from "../db";
import type { AppSettings, AppearanceAsset, Area, BackupPayload, BackupPayloadV1, BackupPayloadV2, BackupPayloadV3, BackupPayloadV4, BackupPayloadV5, DailyReflection, EmotionDefinition, LegacyTask, RestorePreview, Task, TaskLifecycle } from "../types";
import { calculateTaskStats } from "./statisticsService";

type UnknownRecord = Record<string, unknown>;
const tables = [db.areas, db.tasks, db.checkIns, db.experienceLogs, db.taskLifecycles, db.pausePeriods, db.milestoneEvents, db.dailyOrders, db.dailyReflections, db.meditationEntries, db.emotionDefinitions, db.rewards, db.appearanceAssets, db.settings] as const;
const isRecord = (value: unknown): value is UnknownRecord => Boolean(value) && typeof value === "object" && !Array.isArray(value);
function requireArray(record: UnknownRecord, key: string): unknown[] { if (!Array.isArray(record[key])) throw new Error(`Backup field '${key}' must be an array.`); return record[key]; }
function validateItems(items: unknown[], label: string, required: string[]): void { items.forEach((item, index) => { if (!isRecord(item) || required.some((key) => typeof item[key] !== "string")) throw new Error(`${label} entry ${index + 1} is malformed.`); }); }

function validateCore(record: UnknownRecord): void {
  if (record.format !== "daily-canvas-backup") throw new Error("This is not a Daily Canvas backup.");
  if (![1, 2, 3, 4, 5, 6].includes(Number(record.version))) throw new Error("This backup version is not supported.");
  const tasks = requireArray(record, "tasks"), checkIns = requireArray(record, "checkIns"), dailyOrders = requireArray(record, "dailyOrders"), rewards = requireArray(record, "rewards"), settings = requireArray(record, "settings");
  const areas = Number(record.version) >= 3 ? requireArray(record, "areas") : [];
  const reflections = Number(record.version) >= 4 ? requireArray(record, "dailyReflections") : requireArray(record, "journalEntries");
  const experienceLogs = Number(record.version) >= 4 ? requireArray(record, "experienceLogs") : [];
  const emotions = Number(record.version) >= 4 ? requireArray(record, "emotionDefinitions") : [];
  const assets = Number(record.version) >= 4 ? requireArray(record, "appearanceAssets") : [];
  const lifecycles = Number(record.version) >= 5 ? requireArray(record, "taskLifecycles") : [], pauses = Number(record.version) >= 5 ? requireArray(record, "pausePeriods") : [], milestones = Number(record.version) >= 5 ? requireArray(record, "milestoneEvents") : [];
  const meditations = Number(record.version) >= 6 ? requireArray(record, "meditationEntries") : [];
  validateItems(areas, "Area", ["id", "name", "color"]); validateItems(tasks, "Task", ["id", "title", "kind", "startDate"]); validateItems(checkIns, "Check-in", ["id", "taskId", "date", "status"]); validateItems(dailyOrders, "Daily order", ["date"]); validateItems(reflections, "Reflection", ["date"]); validateItems(experienceLogs, "Experience", ["id", "taskId", "date"]); validateItems(meditations, "Meditation", ["id", "content", "createdAt", "updatedAt"]); validateItems(emotions, "Emotion", ["id", "label", "normalizedLabel"]); validateItems(rewards, "Reward", ["id", "title", "trigger"]); validateItems(assets, "Appearance asset", ["id", "kind", "dataUrl"]); validateItems(lifecycles, "Lifecycle", ["taskId", "state"]); validateItems(pauses, "Pause", ["id", "taskId", "startDate", "type"]); validateItems(milestones, "Milestone", ["id", "taskId", "date", "type"]); validateItems(settings, "Settings", ["id", "language", "theme"]);
  tasks.forEach((item) => { const task = item as UnknownRecord; if (!["task", "habit", "avoidance"].includes(String(task.kind))) throw new Error("A task has an unsupported type."); if (Number(record.version) >= 3) { if (!isRecord(task.schedule) || !["fixed", "floating", "quota"].includes(String(task.schedule.mode))) throw new Error("A task has an unsupported schedule."); } else if (!isRecord(task.recurrence) || !["once", "daily", "weekdays", "interval"].includes(String(task.recurrence.type))) throw new Error("A task has an unsupported schedule."); });
  checkIns.forEach((item) => { if (!["done", "lapse", "skipped"].includes(String((item as UnknownRecord).status))) throw new Error("A check-in has an unsupported status."); });
  const unique = (items: unknown[], key: string) => new Set(items.map((item) => String((item as UnknownRecord)[key]))).size === items.length;
  if (![areas, tasks, checkIns, dailyOrders, reflections, experienceLogs, meditations, emotions, rewards, assets, pauses, milestones].every((items, index) => unique(items, index === 3 || index === 4 ? "date" : "id")) || !unique(lifecycles, "taskId")) throw new Error("Backup collections contain duplicate identifiers.");
}

const areaIdFor = (name: string, index: number) => `area-${name.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 28) || "legacy"}-${index + 1}`;
function migrateLegacyTasks(tasks: LegacyTask[], exportedAt: string): { areas: Area[]; tasks: Task[] } {
  const groups = new Map<string, { name: string; color: string }>(); for (const task of tasks) { const name = task.category?.trim(); if (name && !groups.has(name.toLocaleLowerCase())) groups.set(name.toLocaleLowerCase(), { name, color: task.color || "#f4a261" }); }
  const areas = [...groups.values()].map((item, index): Area => ({ id: areaIdFor(item.name, index), name: item.name, color: item.color, sortOrder: index, archived: false, createdAt: exportedAt, updatedAt: exportedAt })); const byName = new Map(areas.map((area) => [area.name.toLocaleLowerCase(), area]));
  return { areas, tasks: tasks.map((old) => { const { category, color, recurrence, ...task } = old; return { ...task, areaId: category?.trim() ? byName.get(category.trim().toLocaleLowerCase())?.id : undefined, colorOverride: color || undefined, schedule: { mode: "fixed", recurrence } }; }) };
}

const systemEmotions = (at: string): EmotionDefinition[] => SYSTEM_EMOTIONS.map(([systemKey, label]) => ({ id: `system-${systemKey}`, label, normalizedLabel: label.toLocaleLowerCase(), systemKey, isSystem: true, archived: false, createdAt: at, updatedAt: at }));
function migrateSettings(settings: Array<Record<string, unknown>>, exportedAt: string, hasTasks: boolean): { settings: AppSettings[]; appearanceAssets: AppearanceAsset[] } {
  const source = settings[0] ?? {}; const background = typeof source.backgroundDataUrl === "string" ? source.backgroundDataUrl : undefined; const appearanceAssets: AppearanceAsset[] = background ? [{ id: "migrated-app-background", kind: "background", mimeType: background.slice(5, background.indexOf(";")) || "image/jpeg", dataUrl: background, createdAt: exportedAt }] : [];
  const backgroundPreferences = defaultBackgroundPreferences(); if (background) backgroundPreferences[0] = { ...backgroundPreferences[0], assetId: appearanceAssets[0].id };
  const { backgroundDataUrl: _removed, ...safe } = source;
  return { appearanceAssets, settings: [{ ...defaultSettings(), ...safe, id: "app", dataVersion: 6, onboardingComplete: typeof safe.onboardingComplete === "boolean" ? safe.onboardingComplete : hasTasks, reflectionPromptsEnabled: typeof safe.reflectionPromptsEnabled === "boolean" ? safe.reflectionPromptsEnabled : true, backgroundPreferences: Array.isArray(safe.backgroundPreferences) ? safe.backgroundPreferences as AppSettings["backgroundPreferences"] : backgroundPreferences }] };
}

function lifecyclesFor(tasks: Task[], checkIns: BackupPayload["checkIns"], at: string): TaskLifecycle[] { return tasks.filter((task) => task.kind !== "task" && task.schedule.mode !== "floating").map((task) => ({ taskId: task.id, state: "building", milestoneSequence: 1, personalBest: calculateTaskStats(task, checkIns.filter((item) => item.taskId === task.id)).personalBest, celebrationPending: false, createdAt: at, updatedAt: at })); }

export function migrateBackup(value: unknown): RestorePreview {
  if (!isRecord(value)) throw new Error("Backup content must be a JSON object."); validateCore(value);
  const sourceVersion = value.version as 1 | 2 | 3 | 4 | 5 | 6; const warnings: string[] = []; let payload: BackupPayload;
  if (sourceVersion === 6) {
    const current = value as unknown as BackupPayload; payload = { ...current, settings: current.settings.length ? current.settings.map((item) => ({ ...defaultSettings(), ...item, dataVersion: 6 })) : [{ ...defaultSettings(), onboardingComplete: current.tasks.length > 0 }] };
  } else if (sourceVersion === 5) {
    const current = value as unknown as BackupPayloadV5; payload = { ...current, version: 6, meditationEntries: [], settings: current.settings.length ? current.settings.map((item) => ({ ...defaultSettings(), ...item, dataVersion: 6 })) : [{ ...defaultSettings(), onboardingComplete: current.tasks.length > 0 }] }; warnings.push("This version 5 backup will be upgraded to the Milestone 7 Meditations format before restore.");
  } else if (sourceVersion === 4) {
    const current = value as unknown as BackupPayloadV4; payload = { ...current, version: 6, taskLifecycles: lifecyclesFor(current.tasks, current.checkIns, current.exportedAt), pausePeriods: [], milestoneEvents: [], meditationEntries: [], settings: current.settings.length ? current.settings.map((item) => ({ ...defaultSettings(), ...item, dataVersion: 6 })) : [{ ...defaultSettings(), onboardingComplete: current.tasks.length > 0 }] }; warnings.push("This version 4 backup will be upgraded through the Milestone 6 lifecycle and Milestone 7 Meditations formats before restore.");
  } else {
    const old = value as unknown as BackupPayloadV1 | BackupPayloadV2 | BackupPayloadV3; const planning = sourceVersion < 3 ? migrateLegacyTasks((old as BackupPayloadV1 | BackupPayloadV2).tasks, old.exportedAt) : { areas: (old as BackupPayloadV3).areas, tasks: (old as BackupPayloadV3).tasks };
    const journalEntries = old.journalEntries ?? []; const dailyReflections: DailyReflection[] = journalEntries.map((item) => ({ date: item.date, emotionIds: [], note: item.content, createdAt: item.updatedAt || old.exportedAt, updatedAt: item.updatedAt || old.exportedAt }));
    const migratedSettings = migrateSettings(old.settings as unknown as Array<Record<string, unknown>>, old.exportedAt, old.tasks.length > 0);
    payload = { format: "daily-canvas-backup", version: 6, exportedAt: old.exportedAt, areas: planning.areas, tasks: planning.tasks, checkIns: old.checkIns, experienceLogs: [], taskLifecycles: lifecyclesFor(planning.tasks, old.checkIns, old.exportedAt), pausePeriods: [], milestoneEvents: [], dailyOrders: old.dailyOrders ?? [], dailyReflections, meditationEntries: [], emotionDefinitions: systemEmotions(old.exportedAt), rewards: old.rewards ?? [], appearanceAssets: migratedSettings.appearanceAssets, settings: migratedSettings.settings };
    warnings.push(`This version ${sourceVersion} backup will be upgraded to the current Milestone 7 data format before restore.`);
  }
  const taskIds = new Set(payload.tasks.map((task) => task.id)); const areaIds = new Set(payload.areas.map((area) => area.id)); const emotionIds = new Set(payload.emotionDefinitions.map((emotion) => emotion.id)); const assetIds = new Set(payload.appearanceAssets.map((asset) => asset.id));
  const orphanCheckIns = payload.checkIns.filter((item) => !taskIds.has(item.taskId)).length; if (orphanCheckIns) warnings.push(`${orphanCheckIns} check-in(s) reference missing tasks and will be ignored.`);
  payload = { ...payload, checkIns: payload.checkIns.filter((item) => taskIds.has(item.taskId)), experienceLogs: payload.experienceLogs.filter((item) => taskIds.has(item.taskId)), taskLifecycles: payload.taskLifecycles.filter((item) => taskIds.has(item.taskId)), pausePeriods: payload.pausePeriods.filter((item) => taskIds.has(item.taskId)), milestoneEvents: payload.milestoneEvents.filter((item) => taskIds.has(item.taskId)), tasks: payload.tasks.map((task) => task.areaId && !areaIds.has(task.areaId) ? { ...task, areaId: undefined } : task), dailyReflections: payload.dailyReflections.map((item) => ({ ...item, emotionIds: item.emotionIds.filter((id) => emotionIds.has(id)) })), settings: payload.settings.map((item) => ({ ...item, backgroundPreferences: item.backgroundPreferences.map((pref) => pref.assetId && !assetIds.has(pref.assetId) ? { ...pref, assetId: undefined } : pref) })) };
  return { payload, sourceVersion, migrated: sourceVersion !== 6, warnings, counts: { areas: payload.areas.length, tasks: payload.tasks.length, checkIns: payload.checkIns.length, experienceLogs: payload.experienceLogs.length, taskLifecycles: payload.taskLifecycles.length, pausePeriods: payload.pausePeriods.length, milestoneEvents: payload.milestoneEvents.length, dailyOrders: payload.dailyOrders.length, dailyReflections: payload.dailyReflections.length, meditations: payload.meditationEntries.length, emotions: payload.emotionDefinitions.length, rewards: payload.rewards.length, appearanceAssets: payload.appearanceAssets.length } };
}

export async function createBackup(): Promise<BackupPayload> {
  const [areas, tasks, checkIns, experienceLogs, taskLifecycles, pausePeriods, milestoneEvents, dailyOrders, dailyReflections, meditationEntries, emotionDefinitions, rewards, appearanceAssets, settings] = await Promise.all(tables.map((table) => table.toArray())) as [BackupPayload["areas"], BackupPayload["tasks"], BackupPayload["checkIns"], BackupPayload["experienceLogs"], BackupPayload["taskLifecycles"], BackupPayload["pausePeriods"], BackupPayload["milestoneEvents"], BackupPayload["dailyOrders"], BackupPayload["dailyReflections"], BackupPayload["meditationEntries"], BackupPayload["emotionDefinitions"], BackupPayload["rewards"], BackupPayload["appearanceAssets"], BackupPayload["settings"]];
  return { format: "daily-canvas-backup", version: 6, exportedAt: new Date().toISOString(), areas, tasks, checkIns, experienceLogs, taskLifecycles, pausePeriods, milestoneEvents, dailyOrders, dailyReflections, meditationEntries, emotionDefinitions, rewards, appearanceAssets, settings };
}
export function downloadBackup(payload: BackupPayload, prefix = "daily-canvas-backup"): void { const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${prefix}-${payload.exportedAt.slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); }
export async function restoreBackup(payload: BackupPayload): Promise<void> { await db.transaction("rw", [...tables], async () => { await Promise.all(tables.map((table) => table.clear())); await Promise.all([db.areas.bulkPut(payload.areas), db.tasks.bulkPut(payload.tasks), db.checkIns.bulkPut(payload.checkIns), db.experienceLogs.bulkPut(payload.experienceLogs), db.taskLifecycles.bulkPut(payload.taskLifecycles), db.pausePeriods.bulkPut(payload.pausePeriods), db.milestoneEvents.bulkPut(payload.milestoneEvents), db.dailyOrders.bulkPut(payload.dailyOrders), db.dailyReflections.bulkPut(payload.dailyReflections), db.meditationEntries.bulkPut(payload.meditationEntries), db.emotionDefinitions.bulkPut(payload.emotionDefinitions), db.rewards.bulkPut(payload.rewards), db.appearanceAssets.bulkPut(payload.appearanceAssets), db.settings.bulkPut(payload.settings)]); const counts = await Promise.all(tables.map((table) => table.count())); const expected = [payload.areas, payload.tasks, payload.checkIns, payload.experienceLogs, payload.taskLifecycles, payload.pausePeriods, payload.milestoneEvents, payload.dailyOrders, payload.dailyReflections, payload.meditationEntries, payload.emotionDefinitions, payload.rewards, payload.appearanceAssets, payload.settings].map((items) => items.length); if (counts.some((count, index) => count !== expected[index])) throw new Error("Restore integrity check failed."); }); await initializeDb(); }
