import { addDays, addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isAfter, isSameMonth, parseISO, startOfMonth, startOfWeek } from "date-fns";
import { useLiveQuery } from "dexie-react-hooks";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { db } from "../db";
import { toDateKey, todayKey } from "../lib/dates";
import { resolveTaskColor } from "../services/areaService";
import { calendarRecordVisibility, calendarTaskSets, type CalendarRecordFilter } from "../services/calendarEvidenceService";
import { setCheckIn } from "../services/checkInService";
import { getQuotaPeriod, getQuotaProgress } from "../services/quotaService";
import { isPausedOn } from "../services/pauseService";
import { isFixedOccurrenceOn, isQuotaAvailableOn } from "../services/scheduleService";
import type { Task } from "../types";

type CalendarMode = "aggregate" | "task" | "area";
export function CalendarView({ weekStartsOn, initialDate = todayKey(), onOpenReflection }: { weekStartsOn: 0 | 1; initialDate?: string; onOpenReflection: (date: string) => void }) {
  const { t, i18n } = useTranslation(); const initial = parseISO(initialDate);
  const [month, setMonth] = useState(startOfMonth(initial)); const [selectedDate, setSelectedDate] = useState(initialDate);
  const [mode, setMode] = useState<CalendarMode>("aggregate"); const [taskId, setTaskId] = useState(""); const [areaId, setAreaId] = useState("");
  const [scheduleMode, setScheduleMode] = useState<"" | Task["schedule"]["mode"]>(""); const [taskKind, setTaskKind] = useState<"" | Task["kind"]>(""); const [recordType, setRecordType] = useState<CalendarRecordFilter>("all");
  const data = useLiveQuery(async () => ({ tasks: await db.tasks.toArray(), areas: await db.areas.toArray(), checkIns: await db.checkIns.toArray(), reflections: await db.dailyReflections.toArray(), emotions: await db.emotionDefinitions.toArray(), experiences: await db.experienceLogs.toArray(), pauses: await db.pausePeriods.toArray(), lifecycles: await db.taskLifecycles.toArray() }), []) ?? { tasks: [], areas: [], checkIns: [], reflections: [], emotions: [], experiences: [], pauses: [], lifecycles: [] };
  const taskSets = useMemo(() => calendarTaskSets(data.tasks, data.lifecycles, { mode, taskId, areaId, scheduleMode, taskKind }), [data.tasks, data.lifecycles, scheduleMode, taskKind, mode, taskId, areaId]);
  const matchingTasks = taskSets.matching; const activeTasks = taskSets.selectable; const activeTaskIds = useMemo(() => new Set(activeTasks.map((task) => task.id)), [activeTasks]); const visibility = calendarRecordVisibility(recordType);
  const taskById = useMemo(() => new Map(data.tasks.map((task) => [task.id, task])), [data.tasks]);
  const recordsByKey = useMemo(() => new Map(data.checkIns.map((item) => [`${item.taskId}:${item.date}`, item])), [data.checkIns]);
  const reflectionsByDate = useMemo(() => new Map(data.reflections.map((item) => [item.date, item])), [data.reflections]);
  const emotionById = useMemo(() => new Map(data.emotions.map((item) => [item.id, item])), [data.emotions]);
  const first = startOfWeek(startOfMonth(month), { weekStartsOn }); const last = endOfWeek(endOfMonth(month), { weekStartsOn }); const monthDays = eachDayOfInterval({ start: first, end: last });
  const weekdays = weekStartsOn === 1 ? ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] : ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
  const selectedReflection = visibility.reflection ? reflectionsByDate.get(selectedDate) : undefined; const selectedExperiences = visibility.experience ? data.experiences.filter((item) => item.date === selectedDate && matchingTasks.some((task) => task.id === item.taskId)) : [];
  const selectedRecords = data.checkIns.filter((item) => item.date === selectedDate && matchingTasks.some((task) => task.id === item.taskId));
  const selectedTasks = matchingTasks.filter((task) => { const record = selectedRecords.find((item) => item.taskId === task.id); if (task.schedule.mode === "fixed") return visibility.fixed && (Boolean(record) || (activeTaskIds.has(task.id) && isFixedOccurrenceOn(task, parseISO(selectedDate)) && !isPausedOn(data.pauses.filter((item) => item.taskId === task.id), selectedDate))); if (task.schedule.mode === "floating") return visibility.floating && record?.status === "done"; return visibility.quota && (record?.status === "done" || (recordType === "all" && activeTaskIds.has(task.id) && isQuotaAvailableOn(task, parseISO(selectedDate)))); });
  const selectedPauses = visibility.pause ? data.pauses.filter((pause) => pause.startDate <= selectedDate && (!pause.endDate || pause.endDate >= selectedDate) && matchingTasks.some((task) => task.id === pause.taskId)) : [];
  const selectDate = (date: Date) => { const dateKey = toDateKey(date); setSelectedDate(dateKey); setMonth(startOfMonth(date)); };
  const keyboardMove = (event: React.KeyboardEvent, date: Date) => { const offsets: Record<string, number> = { ArrowLeft: -1, ArrowRight: 1, ArrowUp: -7, ArrowDown: 7 }; const offset = offsets[event.key]; if (offset) { event.preventDefault(); selectDate(addDays(date, offset)); } };
  const cellState = (date: Date) => {
    const dateKey = toDateKey(date); const past = dateKey < todayKey();
    const scheduled = activeTasks.filter((task) => task.schedule.mode === "fixed" && isFixedOccurrenceOn(task, date)); const pausedTasks = scheduled.filter((task) => isPausedOn(data.pauses.filter((item) => item.taskId === task.id), dateKey)); const due = scheduled.filter((task) => !pausedTasks.includes(task));
    const records = data.checkIns.filter((item) => item.date === dateKey && matchingTasks.some((task) => task.id === item.taskId));
    const done = records.filter((item) => item.status === "done"); const fixedRecords = records.filter((item) => taskById.get(item.taskId)?.schedule.mode === "fixed"); const lapse = fixedRecords.filter((item) => item.status === "lapse").length; const skipped = fixedRecords.filter((item) => item.status === "skipped").length;
    const floating = done.filter((item) => taskById.get(item.taskId)?.schedule.mode === "floating").length; const quota = done.filter((item) => taskById.get(item.taskId)?.schedule.mode === "quota").length;
    const fixedDone = done.filter((item) => taskById.get(item.taskId)?.schedule.mode === "fixed").length; const missed = past ? Math.max(0, due.length - fixedDone - skipped - lapse) : 0;
    return { due: due.length, fixedDone, floating, quota, lapse, skipped, missed, paused: pausedTasks.length, reflection: reflectionsByDate.has(dateKey), experience: data.experiences.some((item) => item.date === dateKey && matchingTasks.some((task) => task.id === item.taskId)) };
  };
  return <div className="view-stack">
    <section className="panel calendar-panel">
      <div className="section-heading"><div><span className="eyebrow">{t("calendarEvidence")}</span><h1>{new Intl.DateTimeFormat(i18n.language, { month: "long", year: "numeric" }).format(month)}</h1><p>{t("calendarReviewHint")}</p></div><div className="month-controls"><button type="button" className="icon-button" onClick={() => setMonth(addMonths(month, -1))} aria-label={t("monthPrevious")}>‹</button><button type="button" className="button secondary" onClick={() => selectDate(new Date())}>{t("today")}</button><button type="button" className="icon-button" onClick={() => setMonth(addMonths(month, 1))} aria-label={t("monthNext")}>›</button></div></div>
      <div className="calendar-toolbar">
        <div className="segmented compact-segmented">{(["aggregate", "task", "area"] as CalendarMode[]).map((item) => <button type="button" className={mode === item ? "active" : ""} key={item} onClick={() => setMode(item)}>{t(`calendarMode_${item}`)}</button>)}</div>
        {mode === "task" && <select aria-label={t("tasks")} value={taskId} onChange={(event) => setTaskId(event.target.value)}><option value="">{t("allTasks")}</option>{calendarTaskSets(data.tasks, data.lifecycles, { mode: "aggregate", taskId: "", areaId: "", scheduleMode: "", taskKind: "" }).selectable.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select>}
        {mode === "area" && <select aria-label={t("areas")} value={areaId} onChange={(event) => setAreaId(event.target.value)}><option value="">{t("allAreas")}</option>{data.areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select>}
        <select aria-label={t("scheduleType")} value={scheduleMode} onChange={(event) => setScheduleMode(event.target.value as typeof scheduleMode)}><option value="">{t("allSchedules")}</option><option value="fixed">{t("fixedSchedule")}</option><option value="floating">{t("floatingTask")}</option><option value="quota">{t("quotaGoal")}</option></select>
        <select aria-label={t("taskKind")} value={taskKind} onChange={(event) => setTaskKind(event.target.value as typeof taskKind)}><option value="">{t("allTaskKinds")}</option><option value="task">{t("regularTask")}</option><option value="habit">{t("goodHabit")}</option><option value="avoidance">{t("avoidanceHabit")}</option></select>
        <select aria-label={t("recordType")} value={recordType} onChange={(event) => setRecordType(event.target.value as CalendarRecordFilter)}><option value="all">{t("allRecords")}</option><option value="check-in">{t("checkIns")}</option><option value="floating">{t("floatingTask")}</option><option value="quota">{t("quotaCredits")}</option><option value="reflection">{t("reflection")}</option><option value="experience">{t("experienceRecords")}</option></select>
      </div>
      <div className="calendar-legend" aria-label={t("calendarLegend")}><span><i className="legend-done">✓</i>{t("done")}/{t("safe")}</span><span><i className="legend-floating">●</i>{t("floatingTask")}</span><span><i className="legend-quota">◆</i>{t("quotaCompletion")}</span><span><i className="legend-pause">Ⅱ</i>{t("pause")}</span><span><i className="legend-skip">∕</i>{t("skipped")}</span><span><i className="legend-lapse">!</i>{t("lapse")}</span><span><i className="legend-missed">○</i>{t("missed")}</span><span><i className="legend-note">✎</i>{t("reflection")}</span><span><i className="legend-empty">·</i>{t("unrecorded")}</span></div>
      <div className="calendar-grid weekday-row">{weekdays.map((item) => <span key={item}>{t(item)}</span>)}</div>
      <div className="calendar-grid month-grid">{monthDays.map((date) => { const dateKey = toDateKey(date); const state = cellState(date); return <button type="button" key={dateKey} className={`calendar-cell evidence-cell ${!isSameMonth(date, month) ? "outside" : ""} ${dateKey === selectedDate ? "selected" : ""} ${dateKey === todayKey() ? "today-cell" : ""}`} onClick={() => selectDate(date)} onKeyDown={(event) => keyboardMove(event, date)} aria-label={`${dateKey}. ${state.fixedDone} ${t("completed")}, ${state.missed} ${t("missed")}, ${state.paused} ${t("pause")}`}><span>{format(date, "d")}</span><div className="cell-evidence">{visibility.fixed && state.fixedDone > 0 && <i className="mark done-mark">✓{state.fixedDone}</i>}{visibility.floating && state.floating > 0 && <i className="mark floating-mark">●{state.floating}</i>}{visibility.quota && state.quota > 0 && <i className="mark quota-mark">◆{state.quota}</i>}{visibility.pause && state.paused > 0 && <i className="mark pause-mark">Ⅱ{state.paused}</i>}{visibility.fixed && state.skipped > 0 && <i className="mark skip-mark">∕{state.skipped}</i>}{visibility.fixed && state.lapse > 0 && <i className="mark lapse-mark">!{state.lapse}</i>}{visibility.fixed && state.missed > 0 && <i className="mark missed-mark">○{state.missed}</i>}{visibility.reflection && state.reflection && <i className="mark note-mark">✎</i>}{visibility.experience && state.experience && <i className="mark experience-mark">≈</i>}</div></button>; })}</div>
    </section>
    <section className="panel date-detail" aria-live="polite"><div className="section-heading compact-heading"><div><span className="eyebrow">{t("supportingRecords")}</span><h2>{t("selectedDate", { date: new Intl.DateTimeFormat(i18n.language, { month: "short", day: "numeric", year: "numeric" }).format(parseISO(selectedDate)) })}</h2></div>{selectedDate <= todayKey() && <button type="button" className="button secondary" onClick={() => onOpenReflection(selectedDate)}>{t("openReflection")}</button>}</div>
      {selectedTasks.length === 0 && !selectedReflection && selectedExperiences.length === 0 && selectedPauses.length === 0 ? <div className="empty-state small"><p>{t("noRecordsOnDate")}</p></div> : <div className="detail-sections">
        {selectedPauses.length > 0 && <div className="record-card"><h3>{t("pause")}</h3>{selectedPauses.map((pause) => <p key={pause.id}>{taskById.get(pause.taskId)?.title} · {t(pause.type === "planned-break" ? "plannedBreak" : pause.type === "vacation" ? "vacation" : "retroactivePause")}</p>)}</div>}
        {selectedTasks.length > 0 && <div><h3>{t("checkIns")}</h3><div className="history-list">{selectedTasks.map((task) => { const record = recordsByKey.get(`${task.id}:${selectedDate}`); const quota = task.schedule.mode === "quota" ? getQuotaProgress(task, getQuotaPeriod(task.schedule, parseISO(selectedDate), weekStartsOn), data.checkIns, parseISO(selectedDate)) : null; return <div className="history-row" key={task.id}><span className="task-color" style={{ background: resolveTaskColor(task, data.areas) }} /><div><strong>{task.title}</strong><span>{task.schedule.mode === "quota" ? `${record?.status === "done" ? t("quotaCompletion") : t("noQuotaCredit")} · ${quota?.count}/${quota?.target}` : record?.status ? t(record.status === "done" && task.kind === "avoidance" ? "safe" : record.status) : t("unrecorded")}</span></div><div className="history-actions"><button disabled={isAfter(parseISO(selectedDate), new Date())} type="button" className={record?.status === "done" ? "active" : ""} onClick={() => setCheckIn(task.id, selectedDate, record?.status === "done" ? undefined : "done")}>{task.kind === "avoidance" ? t("safe") : t("done")}</button>{task.schedule.mode === "fixed" && task.kind === "avoidance" && <button type="button" className={record?.status === "lapse" ? "danger active" : "danger"} onClick={() => setCheckIn(task.id, selectedDate, record?.status === "lapse" ? undefined : "lapse")}>{t("lapse")}</button>}{task.schedule.mode === "fixed" && <button type="button" className={record?.status === "skipped" ? "active" : ""} onClick={() => setCheckIn(task.id, selectedDate, record?.status === "skipped" ? undefined : "skipped")}>{t("skip")}</button>}</div></div>; })}</div></div>}
        {selectedReflection && <div className="record-card"><h3>{t("reflection")}</h3>{selectedReflection.emotionIds.length > 0 && <div className="context-chips">{selectedReflection.emotionIds.map((id) => <span key={id}>{emotionById.get(id)?.label ?? id}</span>)}</div>}{selectedReflection.note && <p>{selectedReflection.note}</p>}</div>}
        {selectedExperiences.length > 0 && <div><h3>{t("experienceRecords")}</h3>{selectedExperiences.map((item) => <div className="record-card" key={item.id}><strong>{taskById.get(item.taskId)?.title}</strong><span>{item.comparison ? t(item.comparison) : t("recorded")}</span>{item.note && <p>{item.note}</p>}</div>)}</div>}
      </div>}
    </section>
  </div>;
}
