import { useState } from "react";
import { useTranslation } from "react-i18next";
import { saveExperience } from "../services/experienceService";
import type { ExperienceComparison, Task } from "../types";

export function ExperienceModal({ task, date, onClose }: { task: Task; date: string; onClose: () => void }) {
  const { t } = useTranslation(); const [comparison, setComparison] = useState<ExperienceComparison>(); const [effort, setEffort] = useState<number>(); const [urge, setUrge] = useState<number>(); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { setSaving(true); await saveExperience({ taskId: task.id, date, comparison, effort, urgeIntensity: task.kind === "avoidance" ? urge : undefined, note }); onClose(); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal-card experience-modal" role="dialog" aria-modal="true" aria-labelledby="experience-title"><div className="section-heading compact-heading"><div><span className="eyebrow">{t("optional")}</span><h2 id="experience-title">{t("howDidItFeel")}</h2><p>{t("experienceHint", { title: task.title })}</p></div><button className="icon-button" type="button" onClick={onClose} aria-label={t("close")}>×</button></div><div className="comparison-grid">{(["easier", "similar", "harder"] as const).map((value) => <button type="button" className={comparison === value ? "active" : ""} key={value} onClick={() => setComparison(value)}>{t(value)}</button>)}</div><label className="field"><span>{t("effort")}</span><select value={effort ?? ""} onChange={(event) => setEffort(event.target.value ? Number(event.target.value) : undefined)}><option value="">{t("notRecorded")}</option>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value}</option>)}</select></label>{task.kind === "avoidance" && <label className="field"><span>{t("urgeIntensity")}</span><select value={urge ?? ""} onChange={(event) => setUrge(event.target.value ? Number(event.target.value) : undefined)}><option value="">{t("notRecorded")}</option>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value}</option>)}</select></label>}<label className="field"><span>{t("shortNote")}</span><textarea value={note} maxLength={280} onChange={(event) => setNote(event.target.value)} placeholder={t("experienceNoteHint")}/></label><div className="form-actions"><button type="button" className="button text-button" onClick={onClose}>{t("notNow")}</button><button type="button" className="button primary" disabled={saving || !(comparison || effort || urge || note.trim())} onClick={submit}>{saving ? t("saving") : t("save")}</button></div></section></div>;
}
