import { useLiveQuery } from "dexie-react-hooks";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { db } from "../db";
import { todayKey } from "../lib/dates";
import { deleteCapture, triageCapture } from "../services/inboxService";
import type { InboxCapture, Schedule, TaskKind } from "../types";
import { Dialog, DialogHeader } from "./Dialog";

function TriageDialog({ capture, onClose }: { capture: InboxCapture; onClose: () => void }) {
  const { t } = useTranslation(); const [mode, setMode] = useState<Schedule["mode"]>("floating"); const [kind, setKind] = useState<TaskKind>("task"); const [date, setDate] = useState(todayKey()); const [target, setTarget] = useState(1); const [error, setError] = useState("");
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const normalizedKind = mode === "floating" ? "task" : mode === "quota" && kind === "task" ? "habit" : kind; const schedule: Schedule = mode === "floating" ? { mode, availableFrom: date } : mode === "quota" ? { mode, period: "week", targetCount: Math.max(1, target), availableFrom: date } : { mode, recurrence: { type: normalizedKind === "task" ? "once" : "daily" } }; await triageCapture(capture.id, { title: capture.title, kind: normalizedKind, starred: false, archived: false, startDate: date, schedule, stopReminderAtTarget: false }); onClose(); } catch { setError(t("saveError")); } };
  return <Dialog labelledBy="triage-title" onClose={onClose}><form className="dialog-body task-form" onSubmit={save}><div className="field-wide"><DialogHeader id="triage-title" eyebrow={t("inbox")} title={capture.title} hint={t("triageHint")} onClose={onClose} closeLabel={t("close")}/></div><label className="field"><span>{t("scheduleType")}</span><select value={mode} onChange={(event) => setMode(event.target.value as Schedule["mode"])}><option value="floating">{t("floatingTask")}</option><option value="fixed">{t("fixedSchedule")}</option><option value="quota">{t("quotaGoal")}</option></select></label>{mode !== "floating" && <label className="field"><span>{t("taskKind")}</span><select value={kind} onChange={(event) => setKind(event.target.value as TaskKind)}>{mode === "fixed" && <option value="task">{t("regularTask")}</option>}<option value="habit">{t("goodHabit")}</option><option value="avoidance">{t("avoidanceHabit")}</option></select></label>}<label className="field"><span>{t(mode === "floating" || mode === "quota" ? "availableFrom" : "startDate")}</span><input required type="date" value={date} onChange={(event) => setDate(event.target.value)}/></label>{mode === "quota" && <label className="field"><span>{t("targetCount")}</span><input type="number" min="1" value={target} onChange={(event) => setTarget(Number(event.target.value))}/></label>}{error && <p className="error-message field-wide" role="alert">{error}</p>}<div className="form-actions field-wide"><button type="button" className="button secondary" onClick={onClose}>{t("cancel")}</button><button type="submit" className="button primary">{t("createTask")}</button></div></form></Dialog>;
}

export function InboxView() { const { t, i18n } = useTranslation(); const captures = useLiveQuery(() => db.inboxCaptures.orderBy("createdAt").reverse().toArray(), []) ?? []; const [triage, setTriage] = useState<InboxCapture>(); return <div className="page page-narrow"><div className="page-intro"><span className="eyebrow">{t("localPrivate")}</span><h2 className="page-title">{t("inbox")}</h2><p className="muted">{t("inboxHint")}</p></div>{captures.length === 0 ? <div className="empty-state"><h3>{t("inboxEmpty")}</h3><p>{t("inboxEmptyHint")}</p></div> : <div className="inbox-list">{captures.map((capture) => <article className="inbox-row" key={capture.id}><div><strong>{capture.title}</strong><small>{new Intl.DateTimeFormat(i18n.language, { dateStyle: "medium", timeStyle: "short" }).format(new Date(capture.createdAt))}</small></div><div className="inline-actions"><button type="button" className="button primary" onClick={() => setTriage(capture)}>{t("triage")}</button><button type="button" className="button text-button danger-text" onClick={() => deleteCapture(capture.id)}>{t("delete")}</button></div></article>)}</div>}{triage && <TriageDialog capture={triage} onClose={() => setTriage(undefined)}/>}</div>; }
