import { useLiveQuery } from "dexie-react-hooks";
import { useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { db } from "../db";
import { deleteAppearanceAsset, importBackground, setBackgroundPreference } from "../services/appearanceService";
import { createBackup, downloadBackup, migrateBackup, restoreBackup } from "../services/backupService";
import { updateSettings } from "../services/settingsService";
import type { SectionId } from "../navigation/workspaceModel";
import type { AppSettings, BackgroundSlot, Language, RestorePreview, Theme } from "../types";

type Operation = "idle" | "saving" | "exporting" | "reading" | "restoring";
const slots: BackgroundSlot[] = ["app", "today", "calendar", "reflection"];
export function SettingsView({ settings, section }: { settings: AppSettings; section: SectionId }) {
  const { t } = useTranslation(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [operation, setOperation] = useState<Operation>("idle"); const [preview, setPreview] = useState<RestorePreview>(); const [slot, setSlot] = useState<BackgroundSlot>("app"); const backgroundInput = useRef<HTMLInputElement>(null); const importInput = useRef<HTMLInputElement>(null); const assets = useLiveQuery(() => db.appearanceAssets.toArray(), []) ?? []; const preference = settings.backgroundPreferences.find((item) => item.slot === slot)!; const asset = assets.find((item) => item.id === preference?.assetId);
  const update = async (changes: Partial<AppSettings>) => { setOperation("saving"); setError(""); try { await updateSettings(changes); setMessage(t("settingsSaved")); } catch { setError(t("saveError")); } finally { setOperation("idle"); } };
  const chooseBackground = async (file?: File) => { if (!file) return; setError(""); try { const imported = await importBackground(file); if (asset) await deleteAppearanceAsset(asset.id); await setBackgroundPreference(slot, { assetId: imported.id }); setMessage(t("settingsSaved")); } catch { setError(t("imageError")); } };
  const clear = async () => { if (asset) await deleteAppearanceAsset(asset.id); };
  const exportData = async () => { setOperation("exporting"); setError(""); try { if (await downloadBackup(await createBackup())) setMessage(t("exportSuccess")); } catch { setError(t("exportError")); } finally { setOperation("idle"); } };
  const readImport = async (file?: File) => { if (!file) return; setOperation("reading"); setPreview(undefined); setError(""); try { setPreview(migrateBackup(JSON.parse(await file.text()))); } catch (caught) { setError(caught instanceof Error ? caught.message : t("importError")); } finally { setOperation("idle"); } };
  const confirmRestore = async () => { if (!preview) return; setOperation("restoring"); setError(""); try { if (!(await downloadBackup(await createBackup(), "daily-canvas-safety-backup"))) return; await restoreBackup(preview.payload); setPreview(undefined); setMessage(t("importSuccess")); } catch { setError(t("restoreError")); } finally { setOperation("idle"); } };
  const status = <>{message && <p className="status-message" role="status">{message}</p>}{error && <p className="error-message" role="alert">{error}</p>}</>;
  if (section === "settingsAppearance") return <div className="view-stack settings-stack"><section className="panel"><div className="section-heading"><div><span className="eyebrow">{t("settings")}</span><h2>{t("appearance")}</h2></div>{operation === "saving" && <span className="save-state">{t("saving")}</span>}</div><div className="settings-grid"><label className="setting-row"><span><strong>{t("theme")}</strong></span><select value={settings.theme} onChange={(event) => update({ theme: event.target.value as Theme })}><option value="light">{t("light")}</option><option value="dark">{t("dark")}</option><option value="system">{t("system")}</option></select></label><div className="setting-row background-setting"><span><strong>{t("backgroundSlots")}</strong><small>{t("backgroundPrivacy")}</small></span><div className="background-controls"><select value={slot} onChange={(event) => setSlot(event.target.value as BackgroundSlot)}>{slots.map((item) => <option key={item} value={item}>{t(`slot_${item}`)}</option>)}</select><div className="inline-actions"><button type="button" className="button secondary" onClick={() => backgroundInput.current?.click()}>{asset ? t("replaceImage") : t("chooseImage")}</button>{asset && <button type="button" className="button text-button" onClick={clear}>{t("clearImage")}</button>}</div><input hidden ref={backgroundInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => chooseBackground(event.target.files?.[0])}/>{preference && <div className="background-options"><label>{t("fit")}<select value={preference.fit} onChange={(event) => setBackgroundPreference(slot, { fit: event.target.value as "cover" | "contain" })}><option value="cover">{t("cover")}</option><option value="contain">{t("contain")}</option></select></label><label>{t("position")}<select value={preference.position} onChange={(event) => setBackgroundPreference(slot, { position: event.target.value })}><option value="center">{t("center")}</option><option value="top">{t("top")}</option><option value="bottom">{t("bottom")}</option></select></label><label>{t("overlay")}<input type="range" min="0.2" max="0.85" step="0.05" value={preference.overlayOpacity} onChange={(event) => setBackgroundPreference(slot, { overlayOpacity: Number(event.target.value) })}/></label><label>{t("blur")}<input type="range" min="0" max="12" value={preference.blurPx} onChange={(event) => setBackgroundPreference(slot, { blurPx: Number(event.target.value) })}/></label></div>}</div></div></div>{status}</section></div>;
  if (section === "settingsData") return <div className="view-stack settings-stack"><section className="panel"><div className="section-heading"><div><span className="eyebrow">{t("data")}</span><h2>{t("backupHeading")}</h2><p>{t("dataLocal")}</p></div></div><div className="data-actions"><button disabled={operation !== "idle"} type="button" className="button primary" onClick={exportData}>{operation === "exporting" ? t("exporting") : t("exportData")}</button><button disabled={operation !== "idle"} type="button" className="button secondary" onClick={() => importInput.current?.click()}>{operation === "reading" ? t("readingBackup") : t("importData")}</button><input hidden ref={importInput} type="file" accept="application/json" onChange={(event) => readImport(event.target.files?.[0])}/></div>{preview && <div className="restore-preview"><h3>{t("restorePreview")}</h3><p>{t("restoreCountsV4", preview.counts)}</p>{preview.migrated && <p>{t("backupWillMigrate", { version: preview.sourceVersion })}</p>}{preview.warnings.map((warning) => <p className="warning-message" key={warning}>{warning}</p>)}<p>{t("safetyBackupNotice")}</p><div className="inline-actions"><button type="button" className="button secondary" onClick={() => setPreview(undefined)}>{t("cancel")}</button><button type="button" className="button primary" disabled={operation === "restoring"} onClick={confirmRestore}>{operation === "restoring" ? t("restoring") : t("confirmRestore")}</button></div></div>}{status}</section></div>;
  return <div className="view-stack settings-stack"><section className="panel"><div className="section-heading"><div><span className="eyebrow">{t("settings")}</span><h2>{t("general")}</h2></div>{operation === "saving" && <span className="save-state">{t("saving")}</span>}</div><div className="settings-grid"><label className="setting-row"><span><strong>{t("language")}</strong></span><select value={settings.language} onChange={(event) => update({ language: event.target.value as Language })}><option value="zh-CN">中文</option><option value="en">English</option></select></label><label className="setting-row"><span><strong>{t("weekStartsOn")}</strong><small>{t("weekStartsOnHint")}</small></span><select value={settings.weekStartsOn} onChange={(event) => update({ weekStartsOn: Number(event.target.value) as 0 | 1 })}><option value={1}>{t("monday")}</option><option value={0}>{t("sunday")}</option></select></label><label className="setting-row"><span><strong>{t("reflectionPrompts")}</strong><small>{t("reflectionPromptsHint")}</small></span><input className="switch" type="checkbox" checked={settings.reflectionPromptsEnabled} onChange={(event) => update({ reflectionPromptsEnabled: event.target.checked })}/></label><label className="setting-row"><span><strong>{t("reduceMotion")}</strong></span><input className="switch" type="checkbox" checked={settings.reduceMotion} onChange={(event) => update({ reduceMotion: event.target.checked })}/></label></div>{status}</section></div>;
}
