import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { subDays } from "date-fns";
import { useLiveQuery } from "dexie-react-hooks";
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { db } from "../db";
import { todayKey } from "../lib/dates";
import { resolveTaskColor } from "../services/areaService";
import { setCheckIn } from "../services/checkInService";
import { saveDailyOrder, saveJournal } from "../services/dailyService";
import { getQuotaPeriod, getQuotaProgress, getQuotaStreak } from "../services/quotaService";
import { isQuotaAvailableOn, scheduledTasks } from "../services/scheduleService";
import { calculateTaskStats } from "../services/statisticsService";
import type { Area, CheckIn, Task } from "../types";

function SortableTaskCard({ task, record, checkIns, areas, onEdit }: { task: Task; record?: CheckIn; checkIns: CheckIn[]; areas: Area[]; onEdit: () => void }) {
  const { t } = useTranslation(); const { attributes,listeners,setNodeRef,transform,transition,isDragging } = useSortable({id:task.id}); const stats = calculateTaskStats(task,checkIns); const area=areas.find((item)=>item.id===task.areaId);
  return <article ref={setNodeRef} style={{ transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.55:1 }} className={`task-card ${record?.status??""}`}><button className="drag-handle" type="button" aria-label={t("dragHint")} {...attributes} {...listeners}>⋮⋮</button><span className="task-color" style={{background:resolveTaskColor(task,areas)}}/><button className="task-copy" onClick={onEdit}><span className="task-title">{task.starred&&<span className="star">★</span>}{task.title}</span><span className="task-meta">{area?.name??t(task.kind==="task"?"regularTask":task.kind==="habit"?"goodHabit":"avoidanceHabit")}</span></button><div className="streak-chip"><span>↗</span>{stats.currentStreak}</div><div className="check-actions">{task.kind==="avoidance"?<><button className={record?.status==="done"?"status-button success active":"status-button success"} onClick={()=>setCheckIn(task.id,todayKey(),record?.status==="done"?undefined:"done")}>{t("safeToday")}</button><button className={record?.status==="lapse"?"status-button danger active":"status-button danger"} onClick={()=>setCheckIn(task.id,todayKey(),record?.status==="lapse"?undefined:"lapse")}>{t("lapse")}</button></>:<button className={record?.status==="done"?"round-check checked":"round-check"} aria-label={record?.status==="done"?t("undo"):t("done")} onClick={()=>setCheckIn(task.id,todayKey(),record?.status==="done"?undefined:"done")}>{record?.status==="done"?"✓":""}</button>}<button className={record?.status==="skipped"?"more-button active":"more-button"} onClick={()=>setCheckIn(task.id,todayKey(),record?.status==="skipped"?undefined:"skipped")}>—</button></div>{stats.targetReached&&<span className="milestone-badge">{t("targetReached")}</span>}</article>;
}

export function TodayView({ onEditTask }: { onEditTask:(task:Task)=>void }) {
  const {t,i18n}=useTranslation(); const date=todayKey(); const tasks=useLiveQuery(async()=> (await db.tasks.toArray()).filter((task)=>!task.archived),[])??[]; const areas=useLiveQuery(()=>db.areas.toArray(),[])??[]; const checkIns=useLiveQuery(()=>db.checkIns.toArray(),[])??[]; const order=useLiveQuery(()=>db.dailyOrders.get(date),[date]); const journal=useLiveQuery(()=>db.journalEntries.get(date),[date]); const settings=useLiveQuery(()=>db.settings.get("app"),[]);
  const fixedTasks=useMemo(()=>{const due=scheduledTasks(tasks,new Date()).filter((task)=>!task.stopReminderAtTarget||!task.targetDays||!calculateTaskStats(task,checkIns.filter((item)=>item.taskId===task.id),subDays(new Date(),1)).targetReached);const index=new Map((order?.taskIds??[]).map((id,position)=>[id,position]));return due.sort((a,b)=>(index.get(a.id)??9999)-(index.get(b.id)??9999)||Number(b.starred)-Number(a.starred));},[tasks,order,checkIns]);
  const quotas=tasks.filter((task)=>task.schedule.mode==="quota"&&isQuotaAvailableOn(task,new Date())); const todayRecords=new Map(checkIns.filter((item)=>item.date===date).map((item)=>[item.taskId,item])); const done=fixedTasks.filter((task)=>todayRecords.get(task.id)?.status==="done").length; const progress=fixedTasks.length?Math.round(done/fixedTasks.length*100):0;
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates})); const onDragEnd=async({active,over}:DragEndEvent)=>{if(!over||active.id===over.id)return;const ids=fixedTasks.map((task)=>task.id);await saveDailyOrder(date,arrayMove(ids,ids.indexOf(String(active.id)),ids.indexOf(String(over.id))));};
  return <div className="view-stack"><section className="hero-card"><div><span className="eyebrow">{new Intl.DateTimeFormat(i18n.language,{weekday:"long",month:"long",day:"numeric"}).format(new Date())}</span><h1>{t("today")}</h1><p>{t("appTagline")}</p></div><div className="progress-orbit" style={{"--progress":`${progress*3.6}deg`} as React.CSSProperties}><div><strong>{progress}%</strong><span>{t("todayProgress")}</span></div></div></section>
    <section className="panel"><div className="section-heading compact-heading"><div><h2>{t("fixedToday")}</h2><p>{t("completedCount",{done,total:fixedTasks.length})}</p></div><span className="quiet-hint">{t("dragHint")}</span></div>{fixedTasks.length===0?<div className="empty-state small"><p>{t("emptyToday")}</p></div>:<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><SortableContext items={fixedTasks.map((task)=>task.id)} strategy={verticalListSortingStrategy}><div className="today-list">{fixedTasks.map((task)=><SortableTaskCard key={task.id} task={task} record={todayRecords.get(task.id)} checkIns={checkIns.filter((item)=>item.taskId===task.id)} areas={areas} onEdit={()=>onEditTask(task)}/>)}</div></SortableContext></DndContext>}</section>
    {quotas.length>0&&<section className="panel quota-panel"><div className="section-heading compact-heading"><div><h2>{t("quotaGoals")}</h2><p>{t("quotaTodayHint")}</p></div></div><div className="quota-list">{quotas.map((task)=>{if(task.schedule.mode!=="quota")return null;const period=getQuotaPeriod(task.schedule,new Date(),settings?.weekStartsOn??1);const records=checkIns.filter((item)=>item.taskId===task.id);const quota=getQuotaProgress(task,period,records);const area=areas.find((item)=>item.id===task.areaId);return <article className="quota-card" key={task.id} style={{"--task-color":resolveTaskColor(task,areas)} as React.CSSProperties}><span className="task-color"/><button className="task-copy" onClick={()=>onEditTask(task)}><span className="task-title">{task.title}</span><span className="task-meta">{area?.name??t("noArea")} · {t(task.schedule.period==="week"?"thisWeek":"thisMonth")}</span></button><div className="quota-meter"><strong>{quota.count} / {quota.target}</strong><span>{quota.achieved?t("quotaAchieved"):t("inProgress")}</span></div><div className="streak-chip" title={t("periodStreak")}>↗ {getQuotaStreak(task,records,new Date(),settings?.weekStartsOn??1)}</div><button className={todayRecords.get(task.id)?.status==="done"?"round-check checked":"round-check"} aria-label={todayRecords.get(task.id)?.status==="done"?t("undo"):t("done")} onClick={()=>setCheckIn(task.id,date,todayRecords.get(task.id)?.status==="done"?undefined:"done")}>{todayRecords.get(task.id)?.status==="done"?"✓":""}</button></article>;})}</div></section>}
    <section className="panel journal-panel"><div className="section-heading compact-heading"><div><h2>{t("journal")}</h2><p>{t("journalHint")}</p></div><span className="character-count">{t("charsLeft",{count:500-Array.from(journal?.content??"").length})}</span></div><textarea value={journal?.content??""} onChange={(event)=>saveJournal(date,event.target.value)} maxLength={500} placeholder={t("journalHint")}/></section>
  </div>;
}
